# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: USRP 2023
author: Chang-Goo Kim

# Information about where the book exists on the web
repository:
  url: https://github.com/changgoo/usrp2023  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true